# Generated by Django 4.0.5 on 2022-06-17 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_system', models.CharField(blank=True, choices=[('Art', 'Art'), ('Chemistry', 'Chemistry'), ('Technical Devices', 'Technical Devices'), ('Cooking', 'Cooking'), ('Music', 'Music')], max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('Beschreibung', models.CharField(max_length=250)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('matrikelnummer', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('deadline', models.DateField()),
                ('percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
