# Generated by Django 4.0.4 on 2022-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_freedates_alter_cluster_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('matrikelnummer', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
